const questions=[
{topic:'使役動詞',source:'111 會考補考',q:"Don’t let kids ______ bicycles on this busy street; it’s very dangerous.",choices:['A. ride','B. to ride','C. riding','D. are riding'],answer:0,img:'assets/q1.webp',scene:'研磨看到「讓孩子做某事」：let 是叫／讓某人去做。',finger:'let + 人 + 原形動詞',steps:['看到 let + kids + ___','先定位：使役動詞','let 後面的人做什麼？→ 用原形動詞'],explain:'let 已經負責「讓」，後面的動作直接用原形 ride。',one:'let 人做事 → 後面動詞穿「原形制服」。'},
{topic:'感官動詞',source:'112 會考',q:'People got very excited when they watched Ms. Smith ______ at the party.',choices:['A. danced','B. dancing','C. has danced','D. to dance'],answer:1,img:'assets/q2.webp',scene:'研磨看著 Ms. Smith 在派對上跳舞：眼睛「看到某人正在做動作」。',finger:'watch + 人 + V-ing / 原形動詞',steps:['看到 watched + Ms. Smith + ___','先定位：感官動詞','選項中找可接的 V-ing／原形；此題 dancing 符合'],explain:'watch 是感官動詞；題目描述看到她在派對跳舞，選 dancing。',one:'看到 watch / see / hear + 人 → 檢查 V-ing／原形。'},
{topic:'花費動詞',source:'111 會考',q:'Although it took me lots of time ______ a big meal for ten people, I was happy that everyone enjoyed it.',choices:['A. prepare','B. to prepare','C. preparing','D. prepared'],answer:1,img:'assets/q3.webp',scene:'研磨一邊準備大餐、一邊看時間：做這件事「花了很多時間」。',finger:'It takes / took + 人 + 時間 + to V',steps:['看到 It took me lots of time + ___','先定位：花費時間 take','句型直接找 to + 原形動詞'],explain:'take 表示做某事花多少時間，句型是 It took + 人 + 時間 + to V。',one:'It took me time to… = 我花時間去做……'},
{topic:'時態',source:'112 會考',q:'I ______ swimming for several years before I went to this high school. I gave it up because of heavy schoolwork.',choices:['A. have practiced','B. am practicing','C. practiced','D. would practice'],answer:2,img:'assets/q4.webp',scene:'漫畫時間線：以前持續游泳 → 上高中 → 因課業太重停止。',finger:'看完整時間線，不只看 for',steps:['看到 for several years：先別急著選完成式','再看 before I went… / gave it up','事情在過去已結束 → 過去式'],explain:'for 只是線索，不是答案。後文說上高中後放棄游泳，整件事已在過去結束。',one:'時態先看「事情現在還有沒有繼續」。'},
{topic:'動作連接',source:'114 會考',q:'It was very windy this morning. Some of the shirts on the balcony were blown away ______ in the pond.',choices:['A. fell','B. and fell','C. fallen','D. and fallen'],answer:1,img:'assets/q5.webp',scene:'強風吹走衣服，接著衣服又掉進池塘：前後是兩個動作。',finger:'完整動詞 + and + 第二個動詞',steps:['先看到 were blown away：第一個動作已完整','後面還有「掉進池塘」第二個動作','用 and 連接；同為過去 → fell'],explain:'were blown away 已是完整動詞；第二個動作 fell 需要 and 連起來。',one:'先發生 A，再發生 B → 常用 and 把兩個動作接起來。'}];
let index=0,score=0,answered=false,records=[];
const $=id=>document.getElementById(id); const start=$('startScreen'),quiz=$('quizScreen'),finish=$('finishScreen');
function resetReveals(){['hintPanel','fingerprintPanel','fiveSecPanel','resultPanel','nextBtn','fingerprintBtn','fiveSecBtn'].forEach(id=>$(id).classList.add('hidden'));$('hintBtn').classList.remove('hidden');$('hintBtn').setAttribute('aria-expanded','false');answered=false;}
function render(){resetReveals();const x=questions[index];$('topicTag').textContent=x.topic;$('counter').textContent=`${index+1} / ${questions.length}`;$('source').textContent=x.source;$('question').textContent=x.q;$('hintImage').src=x.img;$('sceneCaption').textContent=x.scene;$('fingerprint').textContent=x.finger;$('fiveSec').innerHTML=x.steps.map((s,i)=>`<div class="step"><b>${i+1}</b>　${s}</div>`).join('');$('progressBar').style.width=`${index/questions.length*100}%`;$('scoreMini').textContent=`✓ ${score}`;
 const c=$('choices');c.innerHTML='';x.choices.forEach((t,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=t;b.onclick=()=>answer(i,b);c.appendChild(b);});window.scrollTo({top:0,behavior:'smooth'});}
function answer(i,b){if(answered)return;answered=true;const x=questions[index],ok=i===x.answer;if(ok)score++;records.push({topic:x.topic,ok});[...$('choices').children].forEach((el,j)=>{el.disabled=true;if(j===x.answer)el.classList.add('correct');else if(j===i)el.classList.add('wrong');});$('resultTitle').textContent=ok?`答對！${x.choices[x.answer]}`:`再抓一次指紋｜答案 ${x.choices[x.answer]}`;$('resultTitle').className='result-title '+(ok?'good':'bad');$('resultExplain').textContent=x.explain;$('oneLine').textContent=x.one;$('resultPanel').classList.remove('hidden');$('nextBtn').textContent=index===questions.length-1?'查看總成績 →':'下一題 →';$('nextBtn').classList.remove('hidden');$('scoreMini').textContent=`✓ ${score}`;$('progressBar').style.width=`${(index+1)/questions.length*100}%`;$('resultPanel').scrollIntoView({behavior:'smooth',block:'nearest'});}
$('hintBtn').onclick=()=>{$('hintPanel').classList.remove('hidden');$('fingerprintBtn').classList.remove('hidden');$('hintBtn').setAttribute('aria-expanded','true');$('hintBtn').classList.add('hidden');};
$('fingerprintBtn').onclick=()=>{$('fingerprintPanel').classList.remove('hidden');$('fiveSecBtn').classList.remove('hidden');$('fingerprintBtn').classList.add('hidden');};
$('fiveSecBtn').onclick=()=>{$('fiveSecPanel').classList.remove('hidden');$('fiveSecBtn').classList.add('hidden');};
$('nextBtn').onclick=()=>{if(index<questions.length-1){index++;render();}else showFinish();};
function showFinish(){quiz.classList.add('hidden');finish.classList.remove('hidden');$('finalScore').textContent=`${score} / ${questions.length}`;$('finalMessage').textContent=score===5?'5 題都辨識成功。下一步就是「同考點、換包裝」。':score>=3?'已經抓到大部分指紋；把錯題只重看「指紋＋5 秒辨識」。':'先不用加題量，把這 5 個指紋練到一眼認出。';$('reviewList').innerHTML=records.map(r=>`<div class="review-item ${r.ok?'ok':'no'}">${r.ok?'✓':'↻'} ${r.topic}</div>`).join('');window.scrollTo({top:0,behavior:'smooth'});}
function begin(){index=0;score=0;records=[];start.classList.add('hidden');finish.classList.add('hidden');quiz.classList.remove('hidden');render();}
$('startBtn').onclick=begin;$('retryBtn').onclick=begin;
