import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {makeUnits,flattenUnits,scoreRound} from '../js/core.mjs';
import {createRound,restoreRound,recordAnswer,activeIds,allCompleted,restartCycle,importProgress,saveProgress,loadProgress,PROGRESS_KEY} from '../js/quick-round.mjs';
const banks=[108,111,112,113,114].map(y=>JSON.parse(readFileSync(new URL(`../data/${y}.json`,import.meta.url))));
const units=makeUnits(banks),ids=flattenUnits(units),questions=Object.fromEntries(banks.flatMap(b=>b.questions.map(q=>[q.id,q])));
const blank=()=>({completedQuestionIds:[],current:null});
function answerAll(p){while(!p.current.finished){const id=p.current.questionIds[p.current.index];p=recordAnswer(p,id,questions[id].answer);p={...p,current:restoreRound(p.current,ids)};}return p;}
test('20 consecutive rounds of exactly five, whole groups, no repeats',()=>{let seed=81;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);let p=blank(),seen=new Set();for(let n=0;n<20;n++){p.current=createRound(units,p.completedQuestionIds,random);assert.equal(activeIds(p.current).length,5);for(const unit of units)if(unit.questionIds.some(id=>p.current.questionIds.includes(id)))assert.ok(unit.questionIds.every(id=>p.current.questionIds.includes(id)));for(const id of activeIds(p.current)){assert.ok(!seen.has(id));seen.add(id);}p=answerAll(p);}assert.equal(seen.size,100);});
test('entire eligible pool terminates without repeats; six-question group remains unaltered',()=>{let p=blank(),seen=new Set();while(true){p.current=createRound(units,p.completedQuestionIds);if(!p.current)break;assert.ok(activeIds(p.current).length<=5);for(const id of activeIds(p.current)){assert.ok(!seen.has(id));seen.add(id);}p=answerAll(p);}assert.equal(seen.size,205);assert.deepEqual(ids.filter(id=>!seen.has(id)),['CAP-114-38','CAP-114-39','CAP-114-40','CAP-114-41','CAP-114-42','CAP-114-43']);assert.equal(allCompleted(ids,p),false);});
test('exact combination beats greedy short round; impossible remainder stays short',()=>{const fake=[{questionIds:['a','b','c','d']},{questionIds:['e','f','g']},{questionIds:['h','i']}];assert.equal(activeIds(createRound(fake,[],()=>0.999)).length,5);assert.equal(activeIds(createRound(fake.slice(0,2),[],()=>0.999)).length,4);assert.equal(createRound([{questionIds:['a','b','c','d','e','f']}],[]),null);});
test('0/1/4/5 remaining never refill with completed questions',()=>{for(const n of [0,1,4,5]){const remaining=units.filter(u=>u.questionIds.length===1).slice(0,n).flatMap(u=>u.questionIds);const s=createRound(units,ids.filter(id=>!remaining.includes(id)));assert.equal(s?activeIds(s).length:0,n);}});
test('answer correct or wrong marks completed once; unanswered does not',()=>{let p=blank();p.current=createRound(units,[]);const id=p.current.questionIds[p.current.index];assert.equal(p.completedQuestionIds.length,0);p=recordAnswer(p,id,questions[id].answer);assert.deepEqual(p.completedQuestionIds,[id]);assert.equal(recordAnswer(p,id,'A'),p);p.current=restoreRound(p.current,ids);const next=p.current.questionIds[p.current.index];p=recordAnswer(p,next,['A','B','C','D'].find(a=>a!==questions[next].answer));assert.equal(p.completedQuestionIds.length,2);assert.equal(scoreRound(activeIds(p.current),p.current.answers,questions).score,1);});
test('reload resumes first unanswered with identical IDs and answers',()=>{let p=blank();p.current=createRound(units,[]);const original=[...p.current.questionIds];const id=original[p.current.index];p=recordAnswer(p,id,'A');const copy=JSON.parse(JSON.stringify(p));copy.current=restoreRound(copy.current,ids);assert.deepEqual(copy.current.questionIds,original);assert.deepEqual(copy.current.answers,p.current.answers);assert.notEqual(copy.current.questionIds[copy.current.index],id);assert.deepEqual(restoreRound(copy.current,ids),copy.current);});
test('all answered restores completion, explicit restart only at end of full cycle',()=>{let p=blank();p.current=createRound(units,[]);p=answerAll(p);assert.equal(restoreRound(p.current,ids).finished,true);assert.throws(()=>restartCycle(ids,p));p.completedQuestionIds=[...ids];assert.equal(createRound(units,p.completedQuestionIds),null);assert.deepEqual(restartCycle(ids,p),blank());assert.equal(p.completedQuestionIds.length,211);});
test('partial legacy groups retain all references, never re-answer completed members',()=>{const u=units.find(u=>u.questionIds.length>2),remaining=u.questionIds.slice(1),done=ids.filter(id=>remaining.indexOf(id)<0);const s=createRound(units,done);assert.deepEqual(s.questionIds,u.questionIds);assert.deepEqual(activeIds(s),remaining);assert.deepEqual(s.completedBefore,[u.questionIds[0]]);});
test('legacy imports only valid actual answers, never just scheduled IDs',()=>{const legacy={answers:{[ids[0]]:'A',[ids[1]]:'D',junk:'B',[ids[2]]:'?'}};const p=importProgress(ids,null,[legacy,{answers:{[ids[0]]:'A'}}]);assert.deepEqual(p.completedQuestionIds,[ids[0],ids[1]]);assert.deepEqual(importProgress(ids,blank(),[legacy]),blank());});
test('storage persists across reads; only progress key written',()=>{const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};let p=blank();p.current=createRound(units,[]);p=recordAnswer(p,p.current.questionIds[p.current.index],'A');assert.equal(saveProgress(p),true);assert.deepEqual(loadProgress(ids),p);assert.deepEqual([...memory.keys()],[PROGRESS_KEY]);globalThis.localStorage.setItem=()=>{throw Error('quota')};assert.equal(saveProgress(p),false);assert.deepEqual(loadProgress(ids),p);});
