import test from 'node:test';
import assert from 'node:assert/strict';
import {STREAK_KEY,readStreak,checkIn,localDate,streakView,streakMessage,roundQualifies} from '../js/streak.mjs';
const date=d=>new Date(`${d}T12:00:00`);
function storage(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),data};}
test('first day / same day / next day / third day / missed day',()=>{const s=storage();for(const [d,n,total] of [['2026-10-03',1,1],['2026-10-03',1,1],['2026-10-04',2,2],['2026-10-05',3,3],['2026-10-07',1,4]]){const r=checkIn(s,date(d));assert.equal(r.state.currentStreak,n);assert.equal(r.state.totalCompletedDays,total);assert.equal(r.state.lastCompletedDate,d);}assert.deepEqual([...s.data.keys()],[STREAK_KEY]);});
test('persisted reload and homepage today/yesterday/expired read only',()=>{const s=storage();checkIn(s,date('2026-10-03'));const raw=s.getItem(STREAK_KEY);assert.equal(readStreak(s).currentStreak,1);assert.deepEqual(streakView(readStreak(s),date('2026-10-03')),{count:1,todayDone:true});assert.deepEqual(streakView(readStreak(s),date('2026-10-04')),{count:1,todayDone:false});assert.deepEqual(streakView(readStreak(s),date('2026-10-05')),{count:0,todayDone:false});assert.equal(s.getItem(STREAK_KEY),raw);});
test('local date, midnight, month/year/leap/DST boundaries',()=>{assert.equal(localDate(new Date(2026,9,3,0,5)),'2026-10-03');for(const [a,b]of [['2026-12-31','2027-01-01'],['2028-02-28','2028-02-29'],['2026-03-08','2026-03-09']]){const s=storage();checkIn(s,date(a));assert.equal(checkIn(s,date(b)).state.currentStreak,2);}});
test('round requires all answers and at least five; wrong answers count too',()=>{const ids=['a','b','c','d','e','f'];assert.equal(roundQualifies({answers:{a:'A',b:'B',c:'C',d:'D'}},ids.slice(0,4)),false);const answers=Object.fromEntries(ids.map(id=>[id,'A']));assert.equal(roundQualifies({answers},ids.slice(0,5)),true);assert.equal(roundQualifies({answers},ids),true);delete answers.f;assert.equal(roundQualifies({answers},ids),false);});
test('milestones',()=>{assert.deepEqual([1,3,7,14,30,4].map(streakMessage),['第一天完成！','連續 3 天了！','一週達成！','兩週連續打卡！','30 天達成！','連續 4 天，繼續保持！']);});
test('storage failures do not throw or falsely claim saved',()=>{const s={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}};assert.equal(readStreak(s).currentStreak,0);assert.equal(checkIn(s,date('2026-10-03')).saved,false);});
