import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {validateBank,makeUnits,chooseUnits,flattenUnits,scoreRound} from '../js/core.mjs';
import {ADDITIONAL_PASSAGES} from '../data/passages-111-113.mjs';
const root=new URL('../../',import.meta.url);
const banks=[108,111,112,113,114].map(y=>validateBank(JSON.parse(readFileSync(new URL(`exam/data/${y}.json`,root)))));
const all=banks.flatMap(b=>b.questions),groups=banks.flatMap(b=>b.groups),byId=Object.fromEntries(all.map(q=>[q.id,q])),units=makeUnits(banks);
const keys={111:'AACCBABBADCB DCB C D C A D C C D C A C A D B D A D D B D B C B A D C A A'.replaceAll(' ',''),112:'BDDBABACCD D C C C D C C B D C A B D B B A A C D B A A D C B D D B B C B A A'.replaceAll(' ',''),113:'ACBB D D B D C D C A A A C D C D A C B D C C B A D B B A D A A B A B B C C A B B D'.replaceAll(' ','')};
function whole(ids){assert.equal(new Set(ids).size,ids.length);for(const g of groups){const pos=g.questionIds.map(id=>ids.indexOf(id));if(pos.some(n=>n>=0)){assert.ok(pos.every(n=>n>=0),g.id);assert.deepEqual(pos,pos.map((_,i)=>pos[0]+i),g.id);}}}
test('213 raw, 211 approved, 2 review; all permanent IDs unique',()=>{assert.equal(all.length,213);assert.equal(new Set(all.map(q=>q.id)).size,213);assert.equal(flattenUnits(units).length,211);assert.deepEqual(all.filter(q=>q.status==='review').map(q=>q.id),['CAP-112-01','CAP-113-05']);});
test('new years have 43 source questions, original answer evidence and complete options',()=>{for(const b of banks.filter(b=>[111,112,113].includes(b.year))){assert.equal(b.questions.length,43);assert.equal(keys[b.year].length,43);assert.equal(b.questions.map(q=>q.answer).join(''),keys[b.year]);for(const [i,q]of b.questions.entries()){assert.equal(q.questionNumber,i+1);assert.equal(q.id,`CAP-${b.year}-${String(i+1).padStart(2,'0')}`);assert.ok(q.answerVerification.evidence);assert.ok(q.answerVerification.slide>1);assert.equal(q.answerVerification.evidence,q.explanation);assert.deepEqual(Object.keys(q.choices),['A','B','C','D']);for(const k of 'ABCD')assert.ok(q.choices[k]||q.optionImages[k],q.id+' '+k);}}});
test('source group boundaries are complete and exclude no group members',()=>{const ranges={111:[[21,22],[23,24],[25,26],[27,29],[30,32],[33,36],[37,39],[40,43]],112:[[24,25],[26,27],[28,29],[30,32],[33,35],[36,38],[39,41],[42,43]],113:[[22,23],[24,25],[26,27],[28,29],[30,32],[33,35],[36,39],[40,43]]};assert.equal(groups.length,41);for(const b of banks.filter(b=>ranges[b.year]))assert.deepEqual(b.groups.map(g=>[g.firstQuestion,g.lastQuestion]),ranges[b.year]);whole(flattenUnits(units));});
test('quick/mock/random and annual selections preserve whole groups and reject reviews',()=>{let seed=81;const rng=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);for(let i=0;i<100;i++)for(const mode of ['quick','mock','random']){const ids=flattenUnits(chooseUnits(units,{mode},rng));whole(ids);assert.ok(ids.every(id=>byId[id].status==='approved'));if(mode!=='random'){const n=mode==='mock'?20:10;assert.ok(ids.length>=n&&ids.length<=n+5);}}for(const [y,n]of [[108,41],[111,43],[112,42],[113,42],[114,43]]){const ids=flattenUnits(chooseUnits(units,{mode:'year',year:y}));whole(ids);assert.equal(ids.length,n);assert.ok(ids.every(id=>byId[id].year===y));}});
test('retry restores the entire original group; scoring remains unchanged',()=>{const ids=flattenUnits(chooseUnits(units,{mode:'retry',wrongQuestionIds:['CAP-112-31','CAP-113-02']}));whole(ids);assert.deepEqual(new Set(ids),new Set(['CAP-112-30','CAP-112-31','CAP-112-32','CAP-113-02']));const answers=Object.fromEntries(ids.map(id=>[id,byId[id].answer]));answers['CAP-113-02']='A';assert.equal(scoreRound(ids,answers,byId).score,3);});
test('all original images resolve and retain recorded pixel asset hashes',()=>{for(const b of banks.filter(b=>[111,112,113].includes(b.year))){const referenced=b.questions.flatMap(q=>[...q.images,...Object.values(q.optionImages)]).concat(b.groups.flatMap(g=>g.passageImages));for(const path of referenced){assert.ok(existsSync(new URL('exam/'+path,root)),path);assert.ok(b.assetProvenance.some(a=>a.path===path));}for(const a of b.assetProvenance){const bytes=readFileSync(new URL('exam/'+a.path,root));assert.equal(createHash('sha256').update(bytes).digest('hex'),a.sha256);assert.ok(bytes.readUInt32BE(16)>0&&bytes.readUInt32BE(20)>0);}}});
test('15 new HTML passages keep original source reference and needed visuals',()=>{assert.equal(Object.keys(ADDITIONAL_PASSAGES).length,15);for(const [id,p]of Object.entries(ADDITIONAL_PASSAGES)){assert.ok(groups.some(g=>g.id===id));assert.ok(p.paragraphs.length&&p.paragraphs.every(Boolean));assert.ok(p.sourceVerification.sha256);for(const f of p.illustrations||[])assert.ok(existsSync(new URL('exam/'+f,root)));}assert.deepEqual(ADDITIONAL_PASSAGES['CAP-113-G40-43'].blankNumbers,[40,41,42,43]);assert.ok(ADDITIONAL_PASSAGES['CAP-111-G30-32'].illustrations.length);});
test('conflicting/universal-credit source evidence is retained but never drawn',()=>{assert.ok(byId['CAP-112-01'].sourceScoringNote.includes('一律給分'));assert.ok(byId['CAP-113-05'].answerVerification.answerOverlay.includes('(A) colors'));assert.ok(byId['CAP-113-05'].explanation.includes('(D)'));for(const id of ['CAP-112-01','CAP-113-05'])assert.ok(!flattenUnits(units).includes(id));});

test("existing 108/114, scoring, storage and passage source remain byte-identical",()=>{const expected={"exam/data/108.json": "13fd01a58ef1bd68e167667539ab02124a89a34f3202d3bd41d29bb167a7c3b5", "exam/data/114.json": "e1a0c036cc28feb2da7d669a4db9f5b1326268da04bf7f5c1345ab8d3a88226d", "exam/data/passages.mjs": "efcc23d556e8d14e08ce2c990ae38c6dc3e9cadc4e2fe27170c606ac9d5411ea", "exam/js/core.mjs": "a6aed1bfc4bf82ad2342a58583c7162a89955a0112e216794104831273de38da", "exam/js/store.mjs": "e758bbabe40694a461311977c25651b8055c71765e614fb3d0d27da98a1d3994"};for(const [p,sha]of Object.entries(expected))assert.equal(createHash("sha256").update(readFileSync(new URL(p,root))).digest("hex"),sha,p);});
